version: "3"

services:
  postgres:
    container_name: matcha-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - matcha_network
    restart: always

networks:
  matcha_network:
    name: matcha_network

volumes:
  database:
