version: "3"

services:
  db:
    container_name: matcha-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - matcha_network
    restart: always

  api:
    container_name: matcha-api
    image: matcha-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - matcha_network
    restart: always

networks:
  matcha_network:
    name: matcha_network

volumes:
  database:
